import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:intl/intl.dart';

const apiBase = String.fromEnvironment('API_BASE_URL', defaultValue: 'http://127.0.0.1:8003');
const green = Color(0xFF2F8F46);
const darkGreen = Color(0xFF0D5B2A);
const yellow = Color(0xFFFFDE00);
final moneyFmt = NumberFormat.currency(locale: 'es_PE', symbol: 'S/ ');

void main() => runApp(const App());

class App extends StatefulWidget { const App({super.key}); @override State<App> createState()=>_AppState(); }
class _AppState extends State<App>{ String? token; Map<String,dynamic>? user; void login(String t, Map<String,dynamic> u){setState((){token=t;user=u;});} void logout(){setState((){token=null;user=null;});} @override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'ProEmpresa',theme:ThemeData(colorScheme:ColorScheme.fromSeed(seedColor:green),useMaterial3:true),home:token==null?LoginPage(onLogin:login):HomePage(token:token!,user:user!,onLogout:logout));}

class Api{ Api(this.token); final String token; Map<String,String> get h=>{'Content-Type':'application/json','Authorization':'Bearer $token'}; Future<dynamic> get(String p)async{final r=await http.get(Uri.parse('$apiBase$p'),headers:h); if(r.statusCode>=400) throw Exception(r.body); return jsonDecode(r.body);} Future<dynamic> post(String p, Map b)async{final r=await http.post(Uri.parse('$apiBase$p'),headers:h,body:jsonEncode(b)); if(r.statusCode>=400) throw Exception(r.body); return jsonDecode(r.body);} }

class LoginPage extends StatefulWidget{const LoginPage({super.key,required this.onLogin});final void Function(String,Map<String,dynamic>) onLogin;@override State<LoginPage> createState()=>_LoginPageState();}
class _LoginPageState extends State<LoginPage>{final dni=TextEditingController(text:'12345678');final pass=TextEditingController(text:'1234');bool loading=false;String error='';Future<void> submit()async{setState(()=>loading=true);try{final r=await http.post(Uri.parse('$apiBase/cliente/login'),headers:{'Content-Type':'application/json'},body:jsonEncode({'numero_documento':dni.text.trim(),'password':pass.text}));if(r.statusCode>=400)throw Exception(r.body);final data=jsonDecode(r.body);widget.onLogin(data['access_token'],data['user']??{});}catch(e){setState(()=>error='No se pudo iniciar sesión. Verifique sus datos.');}finally{if(mounted)setState(()=>loading=false);}}@override Widget build(BuildContext context)=>Scaffold(body:Container(decoration:const BoxDecoration(gradient:LinearGradient(colors:[green,darkGreen])),child:Center(child:SingleChildScrollView(padding:const EdgeInsets.all(22),child:Card(elevation:12,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(26)),child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.stretch,children:[Image.asset('assets/logo_proempresa.png'),const SizedBox(height:24),const Text('Banca Móvil ProEmpresa',style:TextStyle(fontWeight:FontWeight.w900,fontSize:28)),const Text('Consulta, opera y solicita créditos desde tu celular.'),const SizedBox(height:16),TextField(controller:dni,decoration:const InputDecoration(labelText:'DNI')),const SizedBox(height:10),TextField(controller:pass,obscureText:true,decoration:const InputDecoration(labelText:'Clave')),if(error.isNotEmpty)Padding(padding:const EdgeInsets.only(top:12),child:Text(error,style:const TextStyle(color:Colors.red,fontWeight:FontWeight.bold))),const SizedBox(height:18),FilledButton(onPressed:loading?null:submit,child:Text(loading?'Ingresando...':'Ingresar'))]))))));}

class HomePage extends StatefulWidget{const HomePage({super.key,required this.token,required this.user,required this.onLogout});final String token;final Map<String,dynamic> user;final VoidCallback onLogout;@override State<HomePage> createState()=>_HomePageState();}
class _HomePageState extends State<HomePage>{int tab=0;bool show=true;late Api api=Api(widget.token);@override Widget build(BuildContext context){final pages=[Inicio(api:api,show:show,onToggle:()=>setState(()=>show=!show)),Solicitud(api:api),MisSolicitudes(api:api),Perfil(user:widget.user,onLogout:widget.onLogout)];return Scaffold(appBar:AppBar(title:const Text('ProEmpresa'),backgroundColor:green,foregroundColor:Colors.white,actions:[IconButton(onPressed:()=>setState(()=>show=!show),icon:Icon(show?Icons.visibility:Icons.visibility_off))]),body:pages[tab],bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const [NavigationDestination(icon:Icon(Icons.home),label:'Inicio'),NavigationDestination(icon:Icon(Icons.request_page),label:'Solicitar'),NavigationDestination(icon:Icon(Icons.list_alt),label:'Solicitudes'),NavigationDestination(icon:Icon(Icons.person),label:'Más')]),);}}
class Inicio extends StatefulWidget{const Inicio({super.key,required this.api,required this.show,required this.onToggle});final Api api;final bool show;final VoidCallback onToggle;@override State<Inicio> createState()=>_InicioState();}
class _InicioState extends State<Inicio>{late Future<List<dynamic>> cuentas;late Future<List<dynamic>> movs;@override void initState(){super.initState();cuentas=widget.api.get('/cliente/cuentas').then((v)=>v as List);movs=widget.api.get('/cliente/movimientos').then((v)=>v as List);} @override Widget build(BuildContext context)=>RefreshIndicator(onRefresh:()async{setState((){cuentas=widget.api.get('/cliente/cuentas').then((v)=>v as List);movs=widget.api.get('/cliente/movimientos').then((v)=>v as List);});},child:ListView(padding:const EdgeInsets.all(16),children:[Image.asset('assets/logo_proempresa.png'),const SizedBox(height:16),const Text('Mis cuentas',style:TextStyle(fontWeight:FontWeight.w900,fontSize:22)),FutureBuilder<List>(future:cuentas,builder:(c,s){if(!s.hasData)return const Center(child:CircularProgressIndicator());return Column(children:s.data!.map((x)=>Card(child:ListTile(title:Text(x['tipo_cuenta']??''),subtitle:Text(widget.show?(x['numero_cuenta']??''):'••••••••••'),trailing:Text(widget.show?moneyFmt.format(double.parse('${x['saldo_disponible']}')):'S/ ••••',style:const TextStyle(fontWeight:FontWeight.w900)) )) .toList());}),const SizedBox(height:16),const Text('Últimos movimientos',style:TextStyle(fontWeight:FontWeight.w900,fontSize:22)),FutureBuilder<List>(future:movs,builder:(c,s){if(!s.hasData)return const SizedBox();return Column(children:s.data!.map((x)=>Card(child:ListTile(title:Text(x['concepto']??''),subtitle:Text(x['tipo_movimiento']??''),trailing:Text(widget.show?moneyFmt.format(double.parse('${x['monto']}')):'S/ ••••')))).toList());})]));}
class Solicitud extends StatefulWidget{const Solicitud({super.key,required this.api});final Api api;@override State<Solicitud> createState()=>_SolicitudState();}
class _SolicitudState extends State<Solicitud>{final monto=TextEditingController(text:'3000');final plazo=TextEditingController(text:'12');final destino=TextEditingController(text:'Capital de trabajo');String msg='';bool loading=false;Future<void> enviar()async{setState(()=>loading=true);try{final m=double.parse(monto.text);final p=int.parse(plazo.text);final cuota=(m*1.18)/p;final r=await widget.api.post('/cliente/solicitudes',{'monto_solicitado':m,'plazo_meses':p,'destino_credito':destino.text,'cuota_estimada':cuota,'tea_referencial':38.5});setState(()=>msg='Solicitud registrada: ${r['numero_expediente']}');}catch(e){setState(()=>msg='No se pudo registrar la solicitud.');}finally{if(mounted)setState(()=>loading=false);}}@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(16),children:[const Text('Solicitar préstamo',style:TextStyle(fontWeight:FontWeight.w900,fontSize:26)),const Text('La solicitud se enviará al Core y aparecerá en Fuerza de Ventas para la visita del asesor.'),const SizedBox(height:16),TextField(controller:monto,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Monto solicitado')),TextField(controller:plazo,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Plazo en meses')),TextField(controller:destino,decoration:const InputDecoration(labelText:'Destino del crédito')),const SizedBox(height:18),FilledButton(onPressed:loading?null:enviar,child:Text(loading?'Enviando...':'Enviar solicitud')),if(msg.isNotEmpty)Card(child:Padding(padding:const EdgeInsets.all(16),child:Text(msg,style:const TextStyle(fontWeight:FontWeight.bold))))]);}
class MisSolicitudes extends StatefulWidget{const MisSolicitudes({super.key,required this.api});final Api api;@override State<MisSolicitudes> createState()=>_MisSolicitudesState();}
class _MisSolicitudesState extends State<MisSolicitudes>{late Future<List> data;@override void initState(){super.initState();data=widget.api.get('/cliente/solicitudes').then((v)=>v as List);}@override Widget build(BuildContext c)=>FutureBuilder<List>(future:data,builder:(c,s){if(!s.hasData)return const Center(child:CircularProgressIndicator());return ListView(padding:const EdgeInsets.all(16),children:[const Text('Mis solicitudes',style:TextStyle(fontWeight:FontWeight.w900,fontSize:24)),...s.data!.map((x)=>Card(child:ListTile(title:Text(x['numero_expediente']??''),subtitle:Text('${x['destino_credito']??''} · ${x['plazo_meses']} meses'),trailing:Chip(label:Text(x['estado']??'')))))]);});}
class Perfil extends StatelessWidget{const Perfil({super.key,required this.user,required this.onLogout});final Map user;final VoidCallback onLogout;@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(16),children:[Image.asset('assets/logo_proempresa.png'),ListTile(title:Text(user['nombre']??'Cliente'),subtitle:Text(user['numero_documento']??'')),FilledButton.tonal(onPressed:onLogout,child:const Text('Cerrar sesión'))]);}
