import React from 'react';import ReactDOM from 'react-dom/client';import {BrowserRouter,Routes,Route,Navigate,Link,useNavigate} from 'react-router-dom';import {LogOut,Users,ClipboardList,Briefcase,Activity,BarChart3} from 'lucide-react';import api,{setSession,logout,isAuth,user} from './services/api.js';import logo from './assets/logo_proempresa.png';import './styles.css';
function Login(){const nav=useNavigate();const [username,setU]=React.useState('admin');const [password,setP]=React.useState('admin123');const [error,setE]=React.useState('');async function submit(e){e.preventDefault();try{const r=await api.post('/auth/login',{username,codigo_empleado:username,password});setSession(r.data);nav('/');}catch{setE('No se pudo iniciar sesión. Verifique sus credenciales.')}}return <main className="login-page"><form className="login-card" onSubmit={submit}><img src={logo}/><h1>Acceso al Portal Interno</h1><p>Gestión operativa de clientes, cartera, créditos, solicitudes y operaciones.</p><label>Usuario institucional</label><input value={username} onChange={e=>setU(e.target.value)}/><label>Contraseña</label><input type="password" value={password} onChange={e=>setP(e.target.value)}/>{error&&<div className="error">{error}</div>}<button>Ingresar al sistema</button></form></main>}
function Layout({children}){const u=user();return <div className="app"><aside><img src={logo}/><p>Portal Interno</p><Link to="/"><Activity/>Inicio</Link><Link to="/clientes"><Users/>Clientes</Link><Link to="/cartera"><Briefcase/>Cartera</Link><Link to="/solicitudes"><ClipboardList/>Solicitudes</Link><Link to="/operaciones"><BarChart3/>Operaciones</Link><button onClick={logout}><LogOut/>Salir</button></aside><section className="content"><header><b>Core Operativo ProEmpresa</b><span>{u?.username} · {u?.rol}</span></header>{children}</section></div>}
function Private({children}){return isAuth()?<Layout>{children}</Layout>:<Navigate to="/login"/>}
function Dashboard(){const [d,setD]=React.useState(null);React.useEffect(()=>{api.get('/reportes/dashboard').then(r=>setD(r.data))},[]);return <Private><h1>Inicio</h1><div className="cards">{['clientes','solicitudes','cartera_pendiente','operaciones','monto_solicitado'].map(k=><div className="card" key={k}><span>{k.replaceAll('_',' ')}</span><b>{d?.[k]??'...'}</b></div>)}</div></Private>}
function Clientes(){const [data,setData]=React.useState([]);React.useEffect(()=>{api.get('/clientes').then(r=>setData(r.data))},[]);return <Private><h1>Clientes</h1><Table heads={['Documento','Cliente','Teléfono','Negocio','Dirección negocio']} rows={data.map(x=>[x.numero_documento,`${x.nombres} ${x.apellidos}`,x.telefono,x.nombre_negocio,x.direccion_negocio])}/></Private>}
function Cartera(){const [data,setData]=React.useState([]);const load=()=>api.get('/cartera').then(r=>setData(r.data));React.useEffect(load,[]);return <Private><h1>Cartera comercial</h1><Table heads={['Cliente','Solicitud','Monto','Prioridad','Estado visita','Estado solicitud']} rows={data.map(x=>[`${x.nombres} ${x.apellidos}`,x.numero_expediente,'S/ '+Number(x.monto_solicitado||0).toFixed(2),x.prioridad,x.estado_visita,x.estado_solicitud])}/></Private>}
function Solicitudes(){const [data,setData]=React.useState([]);const load=()=>api.get('/solicitudes').then(r=>setData(r.data));React.useEffect(load,[]);async function aprobar(id,monto){await api.patch(`/solicitudes/${id}/estado`,{estado:'aprobada',monto_aprobado:monto,comentario:'Aprobado desde portal'});load();}async function rechazar(id){await api.patch(`/solicitudes/${id}/estado`,{estado:'rechazada',motivo_rechazo:'No cumple política',comentario:'Rechazado desde portal'});load();}return <Private><h1>Solicitudes</h1><table><thead><tr>{['Expediente','Cliente','Monto','Plazo','Estado','Acción'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{data.map(x=><tr key={x.id}><td>{x.numero_expediente}</td><td>{x.nombres} {x.apellidos}</td><td>S/ {Number(x.monto_solicitado).toFixed(2)}</td><td>{x.plazo_meses} meses</td><td><span className="badge">{x.estado}</span></td><td><button className="small" onClick={()=>aprobar(x.id,x.monto_solicitado)}>Aprobar y desembolsar</button><button className="ghost" onClick={()=>rechazar(x.id)}>Rechazar</button></td></tr>)}</tbody></table></Private>}
function Operaciones(){const [data,setData]=React.useState([]);React.useEffect(()=>{api.get('/operaciones').then(r=>setData(r.data))},[]);return <Private><h1>Operaciones</h1><Table heads={['Código','Cliente','Tipo','Monto','Estado','Fecha']} rows={data.map(x=>[x.codigo_operacion,x.cliente_nombre,x.tipo_operacion,'S/ '+Number(x.monto||0).toFixed(2),x.estado,new Date(x.created_at).toLocaleString()])}/></Private>}
function Table({heads,rows}){return <table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c||'-'}</td>)}</tr>)}</tbody></table>}
function App(){return <BrowserRouter><Routes><Route path="/login" element={<Login/>}/><Route path="/" element={<Dashboard/>}/><Route path="/clientes" element={<Clientes/>}/><Route path="/cartera" element={<Cartera/>}/><Route path="/solicitudes" element={<Solicitudes/>}/><Route path="/operaciones" element={<Operaciones/>}/><Route path="*" element={<Navigate to="/"/>}/></Routes></BrowserRouter>}
ReactDOM.createRoot(document.getElementById('root')).render(<App/>);
